version: '3'

services:

  app:
    build: 
      context: app
    networks:
      - node-network
    volumes:
      - ./app:/usr/src/app
    tty: true
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    ports: 
     - "3000:3000"
    depends_on:
      - db

  nginx:
    build: 
      context: nginx-node
    container_name: nginx
    networks:
      - node-network
    ports:
     - "8080:80"
    depends_on:
      - app


  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init-script.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - node-network

networks:
  node-network:
    driver: bridge      

